backend:
  name: github
  repo: iqshadowdigitalmedia/iqshadowdigitalmedia.github.io
  branch: main
  base_url: https://api.netlify.com
  
site_id: fa1eed45-b565-4d98-8dff-d0c45894c120
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
